services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poker-bot-app
    restart: always
    env_file:
      - .env
    environment:
      HTTP_ADDR: 0.0.0.0:8080
    expose:
      - "8080"
    cpus: 1.25
    mem_limit: 768m
    memswap_limit: 1g
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: stas-nginx_proxy
